### ISSUE TITLE
Interchange Power Station broken door

### ISSUE THREAD

**Issue by Somesphinx** [CJ-SPT/Skills-Extended#10]
Hello,
interaction with the door inside the power station on interchange leading to the two smaller rooms is not possible.

A noticification appears:
"[Error  :Skills Extended] Could not find Door ID: Shopping_Mall_2_00041 in location Interchange"

Thanks for the awesome work!

Cheers

**Comment by CJ-SPT** [comment]
Fixed in 1.0.0 with: 3737e6647a0f8cd43c8dc4f555a4f1119380d1b1
