### ISSUE TITLE
Missing door on Woods

### ISSUE THREAD

**Issue by NICKPlayingGames** [CJ-SPT/Skills-Extended#11]
Hi, no clue where else to leave this, error message for the new door on woods attached like the message asked me to do.

![image](https://github.com/user-attachments/assets/f6e646bf-79d3-4d40-8d75-de24940090ca)

**Comment by CJ-SPT** [comment]
Fixed in 1.0.0 with 3737e6647a0f8cd43c8dc4f555a4f1119380d1b1
