### ISSUE TITLE
Meds HP are doubled

### ISSUE THREAD

**Issue by CShigaki** [CJ-SPT/Skills-Extended#12]
Meds hps are doubled even though I'm lvl 0 first aid

![image](https://github.com/user-attachments/assets/d7797688-9188-454c-9d6d-258cdfda1616)

![image](https://github.com/user-attachments/assets/d7456ea1-a739-45a5-8c47-be9163519ca3)

Using Alpha2 version

**Comment by CJ-SPT** [comment]
Thanks for the report, ill look into it. Haven't had a-lot of time to work on the past week

**Comment by CShigaki** [comment]
@CJ-SPT I'm not familiar at all with SPT modding or C# but I believe the problem is either [here](https://github.com/CJ-SPT/Skills-Extended/blob/V1.0.0A2/Plugin/Controllers/FirstAidBehaviour.cs#L34) or [here](https://github.com/CJ-SPT/Skills-Extended/blob/V1.0.0A2/Plugin/Controllers/FirstAidBehaviour.cs#L113)

**Comment by Tetribyte** [comment]
@CJ-SPT I can confirm what @CShigaki suggested with modifying [this line](https://github.com/CJ-SPT/Skills-Extended/blob/V1.0.0A2/Plugin/Controllers/FirstAidBehaviour.cs#L113) to be the following.

`var maxHpResource = Mathf.FloorToInt(_originalMedKitValues[item.TemplateId].MaxHpResource * FaHpBonus);`

This "+ 1" addition is already being accomplished [here](https://github.com/CJ-SPT/Skills-Extended/blob/V1.0.0A2/Plugin/Controllers/FirstAidBehaviour.cs#L34). Tested this in SPT 3.9.4 with a modified DLL and no other changes.

**Comment by CJ-SPT** [comment]
Nice catch, I overlooked that when changing to BSG's buff system.

**Comment by CJ-SPT** [comment]
Fixed with dedf30083e9b22c7f79b685a2ec319955e186ee5
