### ISSUE TITLE
Locale File (Kor) - Thanks :)

### ISSUE THREAD

**Issue by SPT-KorMan** [CJ-SPT/Skills-Extended#18]
{
    "FirstAid": "응급 처치",
    "FirstAidDescription": "응급처치 기술을 통해 의료 키트을 더 빠르고 효과적으로 사용할 수 있습니다.",
    "FirstAidLevelingUpDescription": "의료 키트로 ​​상처를 치료하면 응급처치 기술이 향상됩니다.",
    "FirstAidHealingSpeed": "의료 키트 사용 속도가 [{0:0.#%}] 만큼 증가합니다",
    "FirstAidMaxHp": "의료 키트 자원 수치가 [{0:0.#%}] 만큼 증가합니다",
    "FieldMedicine": "야전 의술",
    "FieldMedicineDescription": "야전 의술 지식을 통해 부목과 붕대를 쉽게 사용할 수 있습니다.",
    "FieldMedicineLevelingUpDescription": "골절이나 출혈을 부목이나 붕대로 치료하면 야전의술 스킬이 향상됩니다.",
    "FieldMedicineSpeed": "부목 및 붕대 감는 속도가 [{0:0.#%}] 만큼 증가합니다.",
    "UsecArsystems": "서구권 무기 숙련도",
    "UsecArsystemsDescription": "서구권 무기 사용에 대한 숙련도",
    "UsecArsystemsLevelingUpDescription": "서구권 무기를 사용하여 타격할 시 향상합니다.",
    "UsecArSystemsErgo": "서구권 무기 인체 공학 수치가 [{0:0.#%}] 만큼 증가합니다.",
    "UsecArSystemsRecoil": "서구권 무기 반동 수치가 [{0:0.#%}] 만큼 감소합니다.",
    "BearAksystems": "동구권 무기 숙련도",
    "BearAksystemsDescription": "동구권 무기 사용에 대한 숙련도",
    "BearAksystemsLevelingUpDescription": "동구권 무기를 사용하여 타격할 시 향상합니다.",
    "BearAkSystemsErgo": "동구권 무기 인체 공학 수치가 [{0:0.#%}] 만큼 증가합니다",
    "BearAkSystemsRecoil": "동구권 무기 반동 수치가 [{0:0.#%}] 만큼 감소합니다",
    "Lockpicking": "자물쇠 따기",
    "LockpickingDescription": "열쇠가 없더라도 자물쇠를 확인하고 열 수 있습니다. 25 레벨이 되면 \"Flipper Zero\" 를 통해 키카드 문을 해킹하는 시도가 가능합니다.",
    "LockpickingLevelingUpDescription": "자물쇠를 검사하고 따는 과정에서 향상됩니다.",
    "LockpickingTimeReduction": "자물쇠를 검사하고 따는 시간이 [{0:0.#%}] 만큼 감소합니다.",
    "LockpickingUseElite": "더 이상 락픽이 부러질 일이 없습니다."
}

**Comment by SPT-KorMan** [comment]
Thank you for your hard work in creating the mod. :)

**Comment by CJ-SPT** [comment]
Of course! Thanks for taking the time to translate it! Will get it into the next update

**Comment by SPT-KorMan** [comment]
Thank you so much. have a good day. 👍

**Comment by CJ-SPT** [comment]
Added with: e14326e49aae13cc73ac5fc7433fbc4cd40a9d90
