### ISSUE TITLE
LockPicking SCAV

### ISSUE THREAD

**Issue by reysonk** [CJ-SPT/Skills-Extended#2]
If the PMCs have lockpicks with them, then the wild can use them in a raid for a SCAV one...This is a bug...

![изображение](https://github.com/CJ-SPT/Skills-Extended/assets/26927358/395ec827-4d1e-4563-a963-cd7aae04c1e7)

**Comment by CJ-SPT** [comment]
Thanks ill fix this in the next patch

**Comment by CJ-SPT** [comment]
Fixed with: https://github.com/CJ-SPT/Skills-Extended/commit/7791a57cc58666746fad31191b5430fe7378b74b
