### ISSUE TITLE
Skills reward balancing issue

### ISSUE THREAD

**Issue by kakahost** [CJ-SPT/Skills-Extended#23]
After updating the mod it gave me too many "Lega" medals. They are too expensive, so I had to destroy them to not destroy my gaming experience. Please, remove them from reward list)

**Comment by kakahost** [comment]
It also gave me deleted quest item - "Documents with decrypted Data"

**Comment by CJ-SPT** [comment]
I nerfed the lega medals last night, I dont really want to completely remove them. I'll keep this open for balancing feed back
