### ISSUE TITLE
ERROR report

### ISSUE THREAD

**Issue by reysonk** [CJ-SPT/Skills-Extended#3]
![изображение](https://github.com/CJ-SPT/Skills-Extended/assets/26927358/cae8031e-f573-4421-a6bf-db0561a9a7c9)

**Comment by reysonk** [comment]
```
Door ID: custom_multiScene_00043 
KeyID: 5913915886f774123603c392 
Key Name: Military checkpoint key
```

**Comment by CJ-SPT** [comment]
Thanks I'll fix this in the next patch

**Comment by CJ-SPT** [comment]
Fixed with: https://github.com/CJ-SPT/Skills-Extended/commit/41f06a056e2f3a820a720b846780cad96b31dc64
