### ISSUE TITLE
FirstAidDescription and FieldMedicineDescription BUG

### ISSUE THREAD

**Issue by reysonk** [CJ-SPT/Skills-Extended#7]
FirstAidDescription and FieldMedicineDescription description with the skill is not shown if you switch the interface language from English to any other

![o1xkkXC](https://github.com/CJ-SPT/Skills-Extended/assets/26927358/3cc31021-f3c8-4ed7-b1c8-a1a3cdc935c6)

```
        this.Instance.database.locales.global.**en**.FirstAidDescription += "FirstAidDescriptionPattern";
        this.Instance.database.locales.global.**en**.FieldMedicineDescription = "FieldMedicineDescriptionPattern";
```

**Comment by CJ-SPT** [comment]
This is no longer relevant, closing.
